FROM ubuntu:20.04

RUN ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y install wget python3 python3-pip pandoc graphviz

LABEL "com.github.actions.name"="Pelican for GitHub Pages"
LABEL "com.github.actions.description"="Builds and deploys the Pelican project to GitHub Pages"
LABEL "com.github.actions.icon"="home"
LABEL "com.github.actions.color"="red"

LABEL "Name"="Pelican for GitHub Pages"
LABEL "Version"="0.0.1"

ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
